# Generated by Django 4.2.6 on 2023-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
